### ISSUE TITLE
Tailwind 4 Intellisense autocomplete not reflecting @theme classes

### ISSUE THREAD

**Issue by teemzero** [tailwindlabs/tailwindcss-intellisense#1155]
Tailwind v4.0.0
Tailwind CSS IntelliSense v0.14.1

Vite 6.0.5, Vue 3.5.13

NodeJS v20.16.0
Chrome
Windows

**Reproduction repo:**
https://github.com/teemzero/tw4_bug

**Issue:**
When I use _./assets/main.css_ instead of _./styles.css_ and I add a class in theme, or change a classname, Intellisense autocomplete doesn't pick up those changes in _App.vue_.
When I switch back to ./styles.css, any changes in theme are directly picked up by the autocompletion in _App.vue_.
This is very consistent behavior.
But. 
There might be a lot more going down, as it took me a while to get to this reproducible situation, and during the process I came across many unexpected behaviors (that I haven't nailed down). 
For now I see that the above situation doesn't apply to _./index.html_, changes in theme classes are not reflected in autocomplete there, which I consider a bug.
You may wanna have an extra look at those neat detection heuristics 🙏thank you for the awesome work.

**Comment by thecrypticace** [comment]
Do you mean you're keeping both files around and expect changes to both sets of themes to show in IntelliSense? Or do you mean that one set of files should be covered by assets/main.css and the other should be covered by styles.css?

If you don't need both, remove one of the files from your project and it'll start working. The main problem here is we're basically detecting two "root" CSS files, they both cover all files, and only one of them wins when IntelliSense asks "which set of classes should I look at for this file".

If you _remove_ either one of the files from the project and reload IntelliSense should start working.Alternatively, if you import one file into the other via `@import` and reload it should also start working.

**Comment by vladmiller** [comment]
@thecrypticace the documentation may need changes, because right now it still references the old .js format.

```
Ensure that you have a Tailwind config file in your workspace and that this is named tailwind.config.{js,cjs,mjs,ts,cts,mts}.
```

In my case, I have a monorepo and naming my file styles.css does not even work by default. Which I guess I kind of expected because how the hell would the extension know where my theme file is. I think with css-first approach there is no default config file name anymore, like we had before with `tailwind.config.js`.

---

@teemzero I was able to solve it by adding this to vscode settings. Also, for when the VSCode extensions misbehave, usually (not always :D), `Restart Extension Host` action fixes these issues.

```
"tailwindCSS.experimental.configFile": "../packages/web-components/styles.css"
```

<img width="674" alt="Image" src="https://github.com/user-attachments/assets/d0d4843b-a0dc-432c-a27e-2040fd86781b" />

**Comment by teemzero** [comment]
Nice one Vlad. 👍
Thanks, I'll use the experimental config file feature.
For restarting I tried Disable and then Enable the extension, that didn't help, but I'll look into 'Restart Extension Host'.

**Comment by vladmiller** [comment]
@teemzero cheers mate, hope it helps.

**Comment by GitDaun** [comment]
@vladmiller Thanks, Vlad!!! Your advice has helped me get through a week that was frustrating. 😃👍

**Comment by PessahDerek** [comment]
I'm facing this issue in webstorm, is there any fix for this?

**Comment by PessahDerek** [comment]
Okay, I fixed this by copying this solution "experimental.configFile": "../packages/web-components/styles.css" to the tailwindcss server configuration file in **Plugins -> Languages & frameworks -> Tailwind CSS**.

But I modified it to **"experimental.configFile": "../**/*.css",** now intellisense is working with the defined themes.
Thanks @vladmiller

**Comment by qingzhoufeihu** [comment]
> [@thecrypticace](https://github.com/thecrypticace) the documentation may need changes, because right now it still references the old .js format.
> 
> ```
> Ensure that you have a Tailwind config file in your workspace and that this is named tailwind.config.{js,cjs,mjs,ts,cts,mts}.
> ```
> 
> In my case, I have a monorepo and naming my file styles.css does not even work by default. Which I guess I kind of expected because how the hell would the extension know where my theme file is. I think with css-first approach there is no default config file name anymore, like we had before with `tailwind.config.js`.
> 
> [@teemzero](https://github.com/teemzero) I was able to solve it by adding this to vscode settings. Also, for when the VSCode extensions misbehave, usually (not always :D), `Restart Extension Host` action fixes these issues.
> 
> ```
> "tailwindCSS.experimental.configFile": "../packages/web-components/styles.css"
> ```
> 
> <img alt="Image" width="674" src="https://private-user-images.githubusercontent.com/1024144/408139511-d0d4843b-a0dc-432c-a27e-2040fd86781b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4OTA3MDAsIm5iZiI6MTc0MDg5MDQwMCwicGF0aCI6Ii8xMDI0MTQ0LzQwODEzOTUxMS1kMGQ0ODQzYi1hMGRjLTQzMmMtYTI3ZS0yMDQwZmQ4Njc4MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMDJUMDQ0MDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2EwYjgzZjQzZWQ3NDI2YjhiMWE2YTZjYjViNTFhMGRkNTMyNzg2ZGQxMmMxZTRjMWI3ZmIwYTQ3YTYyOWU4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1c2pNahrnbbXjB9GnYIc304thIvmtwgMp68NVv9eu3w">
According to your configuration, it still doesn't work

**Comment by sandeep816** [comment]
Tailwind 4 Intellisense autocomplete is still not functioning.

**Comment by labisda** [comment]
Had to downgrade just because of the intelisense. Hope they fix it next time.

**Comment by j3fflan3** [comment]
I used the experimental.configFile in the settings.json...

`"tailwindCSS.experimental.configFile": "src/_styles/global.css"`

Worked for everything but themes.  Gonna fall back to v3 for now. Too much time spent on this.

**Comment by soheilous** [comment]
> Solved it too by using the `configFile` setting. Just wanted to add that I had to remove the `../` prefix in the path. I thought it might be needed because it would resolve from the `.vscode` directory, but that is not the case. For me it resolves from the root. So simply using `packages/web-components/styles.css` (or whatever your directory structure looks like) worked.

Thanks, I also needed to remove `../`

**Comment by eimenanacreado** [comment]
> > Solved it too by using the `configFile` setting. Just wanted to add that I had to remove the `../` prefix in the path. I thought it might be needed because it would resolve from the `.vscode` directory, but that is not the case. For me it resolves from the root. So simply using `packages/web-components/styles.css` (or whatever your directory structure looks like) worked.
> 
> Thanks, I also needed to remove `../`

Same here! by removing ../ it is working for me! thanks

"tailwindCSS.experimental.configFile": "src/library/assets/scss/tailwind-extension.scss"

**Comment by Asce0906** [comment]
i was facing the same issue, my tailwind intellisense doesn't show suggestions/autocompletion !
i tried this :- 

STEP 1 : "tailwindCSS.experimental.configFile": "src/app/globals.css",

STEP 2 : Open the command palette (Ctrl+Shift+P on Windows or Cmd+Shift+P on macOS), 
              then Type and select “Developer: Restart Extension Host”

follow this link it will definitly help you
"https://dev.to/mrpaulishaili/vscode-intellisense-broken-in-tailwind-css-v4-heres-the-solution-4d5"
