### ISSUE TITLE
Issue with cssConflict in Vue class binding ternary

### ISSUE THREAD

**Issue by Ma-An** [tailwindlabs/tailwindcss-intellisense#523]
I am getting a cssConflict when using the same CSS properties with a Vue class binding syntax inside a ternary:

![image](https://user-images.githubusercontent.com/50055607/163252557-7fc8d1b2-04fa-44c1-9cd5-ff7032383927.png)
![image](https://user-images.githubusercontent.com/50055607/163252648-50f11893-222d-4904-9ac4-6494f78bcfe0.png)

This is causing my project to be littered with these warnings. Since these CSS properties are in a ternary statement, they should never be conflicting.

**Comment by tightropeboy** [comment]
Hey, what version are you using ?

**Comment by Ma-An** [comment]
@tightropeboy I am using version 0.8.0, updated from version 0.7.7

**Comment by bradlc** [comment]
Hey @Ma-An, thanks for reporting. This was a regression introduced in `v0.8.0` via #503. That PR has been reverted for now and upgrading to `v0.8.1` should fix the issue 👍

**Comment by buzlo** [comment]
Hello! I still get this error in the current version of the extension (multiple occasions, but not sure what exactly causes the conflict as some classes in ternary go without error): 
![image](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/101005354/6c7d7cc0-2f97-4c46-9b90-f98acb890aa0)

**Comment by unional** [comment]
Same here. Please consider reopen.
https://github.com/biomejs/biome/issues/2224
